#!/usr/bin/env bash

echo "Creating database jobco..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database jobco-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://marciodasilva@localhost:5432/jobco-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
